# Generated by Django 3.2.5 on 2021-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210717_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='student',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Returned', 'Returned')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
